### ISSUE TITLE
Dependency types are outdated

### ISSUE THREAD

**Issue by nikage** [extend-chrome/storage#11]
### Google search terms

I've googled the error: "Namespace 'chrome.accessibilityFeatures' has no exported member 'AccessibilityFeaturesGetArg'."
and found this issue https://github.com/tfoxy/chrome-promise/issues/32 . 
That looks like the types are not updated for typescript in this case.

### Describe the bug

Build fails with this set of errors
```
ERROR in node_modules/chrome-promise/chrome-promise.d.ts:73:51 - error TS2694: Namespace 'chrome.accessibilityFeatures' has no exported member 'AccessibilityFeaturesGetArg'.

73         get(details: chrome.accessibilityFeatures.AccessibilityFeaturesGetArg): Promise<chrome.accessibilityFeatures.AccessibilityFeaturesCallbackArg>;
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/chrome-promise/chrome-promise.d.ts:73:118 - error TS2694: Namespace 'chrome.accessibilityFeatures' has no exported member 'AccessibilityFeaturesCallbackArg'.

73         get(details: chrome.accessibilityFeatures.AccessibilityFeaturesGetArg): Promise<chrome.accessibilityFeatures.AccessibilityFeaturesCallbackArg>;
                                                                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/chrome-promise/chrome-promise.d.ts:81:51 - error TS2694: Namespace 'chrome.accessibilityFeatures' has no exported member 'AccessibilityFeaturesSetArg'.

81         set(details: chrome.accessibilityFeatures.AccessibilityFeaturesSetArg): Promise<void>;
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/chrome-promise/chrome-promise.d.ts:89:53 - error TS2694: Namespace 'chrome.accessibilityFeatures' has no exported member 'AccessibilityFeaturesClearArg'.

89         clear(details: chrome.accessibilityFeatures.AccessibilityFeaturesClearArg): Promise<void>;
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### How do we reproduce?

- `$ npm @extend-chrome/storage:^1.2.1`
- `ng build` (in case of angular app)

### Please complete the following information:

- Library Version: 1.2.1
- Operating System: mac os
- Browser: n/a
- Node Version: v14.9.0

**Comment by nikage** [comment]
From the issue I mentioned above it looks like `@types` dependency should be updated

**Comment by jacksteamdev** [comment]
Between this and #12, it may be time to retire `chrome-promise`. It hasn't been updated since January 2019. 

Converting the `chrome.storage` API to promises would be pretty simple. Anyone who wants to take a swing at the conversion is welcome!

**Comment by jacksteamdev** [comment]
I've just updated the types, so this should be resolved.

**Comment by noccer** [comment]
For future visitors to this issue, the OP found a solution in the `chrome-promise` repo which also worked for me.

I'm adding a link to the fix here for future people coming across this issue (still happening in July 2021):
https://github.com/tfoxy/chrome-promise/issues/33#issuecomment-687896019

PS: thanks for a great library @jacksteamdev, solid work 💪
